name: chinese_english_dictionary
description: A traditional Chinese-English dictionary based on CC-CEDICT.
version: 0.6.1
repository: https://github.com/atn832/chinese_english_dictionary
homepage: https://www.wafrat.com

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
