name: chinese_english_dictionary
description: A Chinese-English dictionary based on CC-CEDICT.
version: 0.6.0
repository: https://github.com/atn832/chinese_english_dictionary
homepage: https://www.wafrat.com

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
